language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - blog_source
# cache this directory
cache:
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - openssl aes-256-cbc -K $encrypted_7f838b6c2cb0_key -iv $encrypted_7f838b6c2cb0_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli # 安装 hexo
  - git clone https://github.com/iissnan/hexo-theme-next themes/next
install:
  - npm install # 安装 package.json 中的插件
script:
  - hexo generate
after_success:
  - git config --global user.name "lasyman"
  - git config --global user.email "xingpeng2010@126.com"
  - sed -i'' "/^ *repo/s~github\.com~${githubToken}@github.com~" _config.yml
  - hexo deploy
# E: Build LifeCycle