language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - blog-source
# cache this directory
cache:
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - openssl aes-256-cbc -K $encrypted_ef3ab21a131e_key -iv $encrypted_ef3ab21a131e_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli # 安装 hexo
  - git clone https://github.com/iissnan/hexo-theme-next themes/next
  - cp themes/_config.yml next
  - cat _confg.yml
install:
  - npm install # 安装 package.json 中的插件
script:
  - hexo generate
after_success:
  - git config --global user.name "lasyman"
  - git config --global user.email "xingpeng2010@126.com"
  - hexo deploy
# E: Build LifeCycle