language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - blog_source
# cache this directory
cache:
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - openssl version
  - openssl aes-256-cbc -K $encrypted_ef3ab21a131e_key -iv $encrypted_ef3ab21a131e_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli # 安装 hexo
  - https://github.com/lasyman/Hexo_Next.git themes/next
install:
  - npm install # 安装 package.json 中的插件
script:
  - hexo generate
after_success:
  - git config --global user.name "lasyman"
  - git config --global user.email "xingpeng2010@126.com"
  - hexo d
# E: Build LifeCycle
