language: node_js
node_js: stable
# assign build branches
branches:
  only:
    - blog_source
#token	
env:
  global:
    secure: 93706756c97f274fbe95375fa904a53298e15780
# cache this directory
cache:
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - export TZ='Asia/Shanghai'
  - npm install -g hexo
  - npm install -g hexo-cli # 安装 hexo
  - git clone https://github.com/iissnan/hexo-theme-next themes/next
before_script:
- git config --global user.name "lasyman"
- git config --global user.email lasyman@163.com
- cp themes/_config.yml next
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
# E: Build LifeCycle